spring:
    application:
        name: blog-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

server:
    port: 8080

#eureka:
#    instance:
#        statusPageUrlPath: /info
#        healthCheckUrlPath: /health
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/